name: kurama-controller

on:
  push:
    branches: [master]
    paths: ['pkg/controller/**']

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

env:
  repo: ghcr.io/iwas-coder/${{ github.workflow }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: setup-qemu
        uses: docker/setup-qemu-action@v3
      - name: setup-buildx
        uses: docker/setup-buildx-action@v3
      - name: login-ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: build-push
        uses: docker/build-push-action@v5
        with:
          push: true
          provenance: false
          file: Containerfile
          context: |
            {{defaultContext}}:pkg/controller
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ${{ env.repo }}:latest
            ${{ env.repo }}:${{ github.sha }}
